name: mixingcolors
description: "A new Flutter project."
publish_to: # It seems like you haven't specified a publish_to field. If you intend to publish your package, you should provide a URL for it.

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1 # Updated to ^0.14.0
  get: ^4.6.6
  provider: ^6.1.2
  intl: ^0.19.0 # Updated to ^0.17.0
  sqflite: ^2.0.0+3 # Updated to ^2.0.0+3
  path_provider: ^2.0.0 # Updated to ^2.0.0
  google_maps_flutter: ^2.0.9 # Updated to ^2.0.9
  flutter_map_location_marker: ^8.0.8
  location: ^6.0.1 # Updated to ^4.3.0
  flutter_polyline_points: ^2.0.0 # Updated to ^0.2.5
  firebase_core: ^2.28.0 # Updated to ^1.10.0
  cloud_firestore: ^4.16.0 # Updated to ^3.1.0
  firebase_auth: ^4.3.0 # Updated to ^4.3.0
  google_sign_in: ^6.2.1 # Updated to ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dotted_line: ^3.2.2
  image_picker: ^1.0.7 # Updated to ^0.8.4+3
  razorpay_flutter: ^1.3.6
  get_storage: ^2.1.1
  flutter_lints: ^3.0.2 # Updated to ^1.0.0
  flutter_svg: ^2.0.10+1
  dots_indicator:

flutter:
  uses-material-design: true
  assets:
    - assets/
